#pragma config(Motor,  port2,           M_F,           tmotorNone, openLoop)
#pragma config(Motor,  port3,           M_R,           tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		motor[M_F] = 100;
		motor[M_R] = 100;
		delay(1000);
		motor[M_F] = 0;
		motor[M_R] = 0;
		delay(1000);
	}

}
